### ISSUE TITLE
Create Chart using API

### ISSUE THREAD

**Issue by reconftw010101** [daniel-hauser/react-organizational-chart#38] opened 2022-08-16 07:27 UTC
**Describe the bug**
React page is loading but Node function calles first not able to create chart with json API. No documentation for that also not able to perform problem is that Node function called at first place before api respondes works perfectly with json file but not able to create with API call.

**To Reproduce**
If applicable, provide a [codesandbox.io](codesandbox.io) example

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**

**Additional context**

**Comment by daniel-hauser** [comment] 2022-08-23 06:41
Can you provide an example?

**Comment by daniel-hauser** [comment] 2022-09-15 18:53
Closing, no example provided and seems like the problem is not related to _react-organizational-chart_.

**Closed by daniel-hauser** 2022-09-15 18:53 UTC
